### ISSUE TITLE
want to add to library bundle?

### ISSUE THREAD

**Issue by ladyada** [vifino/CircuitPython-mitutoyo#1]
hi - this is a great library! please add to our community bundle, it will get automatic releases so people can easily find it :)

https://github.com/adafruit/CircuitPython_Community_Bundle

**Comment by vifino** [comment]
Whoa! Hello! :smile: 
Sure! Now that I cleaned it up some more, made it easier to use and satisfied the CI, I can make a release and then PR it in. :)
Didn't expect all this attention for a simple library I made while playing with Arturo's Serpente. :)

**Comment by ladyada** [comment]
awesome :) thanks! let us know if you need any help

**Comment by vifino** [comment]
Done! :)
